challenges:
    listen:
        port: 2000
        files:
            - listen/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220

    rose:
        port: 2001
        files:
            - rose/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220
        
    scraps:
        port: 2002
        files:
            - scraps/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220

    recipe:
        port: 2003
        files:
            - recipe/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220

    letter:
        port: 2004
        files:
            - letter/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220

    example:
        port: 2005
        files:
            - example/docker-compose.yml
            - common/docker-compose.yml
        commonname: 192.168.254.220
