DEBUG: false

challenges:
    listen:
      port: 2000
      files:
          - listen/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49

    middle:
      port: 2001
      files:
          - middle/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49

    straw:
      port: 2002
      files:
          - straw/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49

    sticks:
      port: 2003
      files:
          - sticks/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49

    brick:
      port: 2004
      files:
          - brick/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49

    segal:
      port: 2005
      files:
          - segal/docker-compose.yml
          - common/docker-compose.yml
      commonname: 35.160.232.49
