version: '2.1'

services:
    catfacts:
        build: ./catfacts/build
        image: naumachia/ntp-rollback.catfacts
        networks:
            default:
                aliases:
                    - "catfacts.naum"
        expose: 
            - "443"
        env_file: chal.env
        environment:
            - PYTHONPATH=/app
        working_dir: /app
        command: ["gunicorn", "-c", "python:config", "catfacts:app"]
        restart: unless-stopped

    ntpproxy:
        build: ./udpproxy
        image: naumachia/udpproxy
        expose:
            - 123/udp
        networks:
            default:
                aliases:
                    - "time.naum"
            external:
        command: ["udpproxy", "--bind-address=0.0.0.0", "--port=123", "--dst-ip=time.google.com", "--dst-port=123"]
        restart: unless-stopped

    client:
        build: ./client/build
        image: naumachia/ntp-rollback.client
        env_file: chal.env
        command: [python, /app/client.py]
        tty: true
        stdin_open: true
        restart: unless-stopped

networks:
    default:
        internal: true
        ipam:
            driver: mini

    # Internet access for ntp service
    external:
        ipam:
            driver: mini
