version: '2.1'

services:
    arthur:
        build: ./actor
        image: naumachia/listen.actor
        env_file: .env
        environment:
            - CHARACTER=Arthur

    bedevere:
        extends: arthur
        environment:
            - CHARACTER=Bedevere

    robin:
        extends: arthur
        environment:
            - CHARACTER=Robin

    bridgekeeper:
        extends: arthur
        environment:
            - CHARACTER=Bridgekeeper

    lancelot:
        extends: arthur
        environment:
            - CHARACTER=Lancelot

    galahad:
        extends: arthur
        environment:
            - CHARACTER=Galahad

networks:
    default:
        internal: true
        ipam:
            driver: mini
