version: '2.1'

services:
    shell:
        build:
            context: ./shell
            args:
                USERNAME: piggy
                PASSWORD: I8elieve1CanFly
                SANDBOX_REPO: https://github.com/nategraf/mini-ipam-driver
                CTF_FLAG: gigem{trust_on_the_internet_is_a_way_to_get_eaten}
        image: naumachia/login-ip.shell
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE
        networks:
            default:

    client:
        image: naumachia/login.client
        command: [python, /app/client.py]
        restart: unless-stopped
        environment:
            SHELL_USER: piggy
            SHELL_PASS: I8elieve1CanFly

networks:
    default:
        internal: true
        ipam:
            driver: mini
