version: '2.1'

services:
    shell:
        build:
            context: ./shell
            args:
                USERNAME: catdaddy
                PASSWORD: 52f8db5543b1a10
                NAUMOTP_SECRET: B46BF20D57BF956C252E7DF7DD540B0E
                SANDBOX_REPO: https://github.com/catdaddy97/catfacts.git
                CTF_FLAG: flag{cats_usuaLly_hAve_9_lives}
        image: naumachia/login-otp/shell
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE

    client:
        image: naumachia/login/client
        command: [python, /app/client.py]
        environment:
            - NAUMOTP_SECRET=B46BF20D57BF956C252E7DF7DD540B0E
            - SHELL_USER=catdaddy
            - SHELL_PASS=52f8db5543b1a10
        restart: unless-stopped

networks:
    default:
        internal: true
        ipam:
            driver: mini
