version: '2.1'

services:
    mailserver:
        build: ./mailserver
        image: naumachia/mail/mailserver
        hostname:  mail
        domainname: naumachia.net
        expose:
            - "25"
            - "143"
        cap_add:
            - NET_BIND_SERVICE
        environment:
            ENABLE_POP3: 1

networks:
    default:
        internal: true
        ipam:
            driver: mini
